### ISSUE TITLE
Running DVID service

### ISSUE THREAD

**Issue by huanxiang** [janelia-flyem/dvid#145] opened 2016-05-03 15:21 UTC
Hello, 

I has just installed the DVID using both docker and the ubuntu installation script, which seems to be successful. However, when I tried to run dvid serve /config/config.toml. I got the following error: 

Unable to initialize datastore: Error loading metadata: Error loading new local ids: Bad value returned for new ids.  Length 0 bytes!

Here is my config file. Is there anything wrong?

Thanks a lot!
Huanxiang

```toml
# Example configuration for DVID

[server]
httpAddress = "127.0.0.1:8000"
rpcAddress = "127.0.0.1:8001"
webClient = "/dvid-console"

# to return Timing-Allow-Origin headers in response
# allowTiming = true

# How new data instance ids are generated.
# Is one of "random" or "sequential".  If "sequential" can set "start_instance_id" property.
instance_id_gen = "sequential"
instance_id_start = 100  # new ids start at least from this.

# Email server to use for notifications and server issuing email-based authorization tokens.
#[email]
#notify = ["foo@someplace.edu"] # Who to send email in case of panic
#username = 
#password = 
#server = 
#port = 25

[logging]
logfile = "/demo/logs/dvid.log"
max_log_size = 500 # MB
max_log_age = 30   # days

[store]   
    # Stores can be specified in three ways (default setting required):
    # store.default  = default storage engine if not otherwise specified
    # store.metadata = configuration for metadata store
    # store.datatype = storage engine to use for the given "datatype"
    # store."name:uuid" = storage engine for a particular data instance, 
    #   where uuid is the full UUID of the repo's root.
    
    [store.default]
    engine = "basholeveldb"
    path = "/demo/dbs/basholeveldb"

    [store.imagetile]
    engine = "basholeveldb"
    path = "/data/tiles" 
```

**Comment by DocSavage** [comment] 2016-05-03 17:44
Hi, Huanxiang,

This is probably due to a big change that's happening in master right now that will allow separate specification of storage systems and assignment from any datatype or data instance.  The config file you are using is a slightly older version of this.

Try using the docker version and then removing the [store.imagetile] part of the config file.

**Comment by huanxiang** [comment] 2016-05-03 19:20
Thanks for the reply.

If I run the docker container, the service seems already running. Do I have to run the server again?

**Comment by DocSavage** [comment] 2016-05-03 19:36
If you modify the config.toml file, you'll need to shutdown and restart the service.  Let me know if you are having issues with the docker version.  Are you running on Linux or Mac?  We'll release user executables for both platforms in the next day or two after we resolve the issue with master.

**Comment by DocSavage** [comment] 2016-05-03 21:32
I've just checked in a couple of commits to master that should resolve any metadata issues if you pull and rebuild.

**Comment by unidesigner** [comment] 2016-05-11 11:31
Hi, I'm seeing the same issue. Is there a configuration file that works with current master? Thanks.

**Comment by DocSavage** [comment] 2016-05-11 13:17
There are two toml files that should always work with the current master: config-simple.toml and config-full.toml in the top-level repo directory.  If you are just setting up a simple (single store) dvid, use the simple version.

**Comment by unidesigner** [comment] 2016-05-12 09:48
I tried config-simple.toml, but I still get "Unable to initialize datastore: Error loading metadata: Error loading new local ids: Bad value returned for new ids.  Length 0 bytes!" and dvid returns. The folder that I specify with the path for the store contains the files "000003.log  CURRENT  LOCK  LOG  MANIFEST-000002  sst_0  sst_1  sst_2  sst_3  sst_4  sst_5  sst_6" after execution of dvid serve. I just changed the webclient, logfile and path variables.

**Comment by DocSavage** [comment] 2016-05-12 13:33
@unidesigner That's odd.  The store path is a new directory with nothing in it or are you trying to reopen an old DVID basholeveldb store?  I'm unable to replicate the issue when starting with a brand new basholeveldb using master code on MacBook Pro.  Can you post your TOML file?

**Comment by unidesigner** [comment] 2016-05-12 15:16
My bad. I wrongly assumed that you need to create the folder before you start dvid with it (even just an empty folder with mkdir). Pointing to a folder that does not exist yet works just fine. Thanks for help!

**Comment by DocSavage** [comment] 2016-05-12 15:30
@unidesigner Creating an empty folder shouldn't cause that kind of error so there is something that needs to be fixed :)

**Comment by unidesigner** [comment] 2016-05-12 15:39
@DocSavage Can you reproduce the same behavior on your MacBook Pro?

**Comment by DocSavage** [comment] 2016-05-12 16:17
@unidesigner Yes.  Submitting commit now that should resolve this for all supported storage including Google Cloud Storage.

**Closed** 2016-05-12 16:17 UTC
